### ISSUE TITLE
Make normal pagination

### ISSUE THREAD

**Issue by LWJerri** [LWJerri/Riddea#30]
Currently, the bot has a very bad pagination system for uploaded messages.

1) When the user opens the latest image, remove the "Next" button.
2) When the user opens the first image, remove the "Back" button.
3) Switch from `new Map()` to npm.js package `telegraf-inline-menu`

**Comment by Satont** [comment]
First 2 punctions can be already easy done i guess. Will do commit with fix it and close issue. Ok?

**Comment by Satont** [comment]
3rd not needed anymore.
